production:
  endpoint: "<%= ENV.fetch('S3_ENDPOINT', 'http://minio:9000') %>"
  bucket_name: lms
  access_key_id: <%= ENV.fetch('S3_ACCESS_KEY', 'minioadmin') %>
  secret_access_key: <%= ENV.fetch('S3_SECRET_KEY', 'minioadmin') %>
  region: us-east-1
  force_path_style: true
