production:
  adapter : postgresql
  encoding: utf8
  host    : <%= ENV.fetch('PGHOST', 'host.docker.internal') %>
  database: <%= ENV.fetch('PGDATABASE', 'canvaslms') %>
  password: <%= ENV.fetch('PGPASSWORD', 'changeme') %>
  username: <%= ENV.fetch('PGUSER', 'postgres') %>
  timeout : 5000
  prepared_statements: false
  use_qualified_names: true
  shard_name: public
  schema_search_path: "''"
