---
assignment_enhancements_teacher_view:
  state: hidden
  applies_to: RootAccount
  display_name: Assignment Enhancements Teacher View (Saved)
  description: Updates to the Teacher saved view of assignments.
assignment_edit_enhancements_teacher_view:
  state: hidden
  applies_to: RootAccount
  display_name: Assignment Enhancements Teacher View (Create/Edit)
  description: Updates to the Teacher create/edit view of assignments.
assign_to_differentiation_tags:
  state: hidden
  applies_to: Account
  shadow: true
  display_name: Assign to Differentiation Tags
  description: Allows instructors to assign course content to differentiation tags via Account/Sub-account setting.
differentiation_tags:
  state: hidden
  applies_to: Course
  display_name: Differentiation Tags
  description: Differentiation Tags allows instructors to create groups of enrolled users that can be used to assign course content.
self_signup_deadline:
  state: hidden
  applies_to: Account
  display_name: Self Sign-up Group Deadline - In Development
  description: Currently in development - Allows teachers to set a deadline for students to sign up for a group within a group set.
people_page_modernization:
  state: hidden
  applies_to: Account
  display_name: People Page Modernization
  description: People page modernization
discussions_speedgrader_revisit:
  state: hidden
  applies_to: Account
  display_name: Discussions SpeedGrader Revisit
  description: Contains improvements to Discussions in Speedgrader. i.e. Toggling, Traversal, Overall experience. Requires react_discussions_post and discussion_checkpoints feature flags to completely work.
deprecate_context_groups_old_view:
  state: hidden
  applies_to: SiteAdmin
  display_name: Deprecate Legacy View of Context Groups
  description: Removes dead code from the context groups view that is no longer used.
  