---
ags_improved_course_concluded_response_codes:
  state: hidden
  display_name: Better LTI AGS Response Codes for Concluded Courses
  description: |-
    If enabled, the AGS API will return a more helpful response code whenever an LTI
    tool attempts to access or modify data in a course that has already concluded.
    Rather than returning a generic 404 Not Found, the API will instead return a 422
    along with a helpful message indicating that the tool cannot access concluded
    courses.
  applies_to: RootAccount
ags_score_trigger_needs_grading_after_submitted:
  state: hidden
  shadow: true
  display_name: Prevents LTI AGS Score publish service incorrectly trigger Needs Grading icon 
  description: |-
    If enabled, the AGS Score publish service endpoint will not trigger showing the Needs Grading icon in the gradebook 
    when activityProgress is Initialized or Started or InProgress just when it is Submitted or Completed.
    If disabled only Initialized activityProgress will not trigger showing the Needs Grading icon in the gradebook.
  applies_to: RootAccount
  environments:
    development:
      state: allowed_on
    ci:
      state: allowed_on
assignment_edit_placement_not_on_announcements:
  state: hidden
  applies_to: SiteAdmin
  display_name: Prevents LTI tools with assignment_edit placement from being launched on Announcements page
  description: When enabled, an LTI tool with the assignment_edit placement will not be launched on the Announcement page.
csrf_oauth2_fix:
  state: hidden
  shadow: true
  applies_to: SiteAdmin
  display_name: Use custom CSRF protection on OAuth2 confirmation page
  description: |-
    If enabled, the standard CSRF token protection will be turned off on the /login/oauth2/accept endpoint.
    Custom CSRF protection will be used instead, which does not use cookies, so it will work better in LTI workflows.
  environments:
    development:
      state: allowed_on
    test:
      state: allowed_on
    ci:
      state: allowed_on
disable_graphql_authentication:
  state: hidden
  display_name: Disable authentication for GraphQL
  description: |-
    If enabled, GraphQL queries will not require
    users to be signed in or use an access token.
  applies_to: SiteAdmin
disable_oembed_retrieve:
  state: hidden
  applies_to: RootAccount
  display_name: Disable oembed_retrieve endpoint
  description: |-
    If enabled, the deprecated oembed_retrieve endpoint will be unavailable.
    This is to ease transitioning any potential users off this endpoint before
    removing it altogether.
  shadow: true
disallow_null_custom_variables:
  state: hidden
  applies_to: SiteAdmin
  display_name: Disallow all null values for custom variables
  description: |-
    When enabled, any custom variables that have previously been returning NULL
    will now return the name of the custom variable.
  environments:
    development:
      state: allowed_on
    ci:
      state: allowed_on
external_tool_drawer:
  state: hidden
  applies_to: RootAccount
  display_name: External Tool Drawer
  description: Enables experimental external tool drawer layout.
  environments:
    development:
      state: allowed_on
    test:
      state: allowed_on
    ci:
      state: allowed_on
import_numeric_lti_custom_params_as_string:
  state: hidden
  shadow: true
  applies_to: SiteAdmin
  display_name: Copy numeric lti custom params as strings on imports.
  description: Prevent ResourceLink custom parameters from being converted to numbers during course copy.
  environments:
    development:
      state: allowed_on
    test:
      state: allowed_on
    ci:
      state: allowed_on
lti_apps_page_instructors:
  state: hidden
  shadow: true
  applies_to: RootAccount
  display_name: LTI Apps Page for Instructors
  description: When enabled, the LTI Apps page will be available in the Course navigation sidebar.
  environments:
    development:
      state: hidden
lti_asset_processor:
  state: hidden
  shadow: true
  applies_to: RootAccount
  display_name: Enable tools to use Asset Processor-related services and placements
  description: |-
    This feature enables LTI tools to create Asset Processors and use services and placements associated
    with the 1EdTech Asset Processor specifications.
  environments:
    development:
      state: allowed_on
    test:
      state: allowed_on
    ci:
      state: allowed_on
lti_before_assignment_results:
  state: hidden
  display_name: Display LTI placement before assignment description after submitting.
  description: |-
    If enabled, the assignment_view LTI placement iframe will be shown above the assignment description if the student has a submission
    and can view the assignment. This can be used to make the placement more prominent for tools that require action after an assignment
    has been submitted.
  applies_to: RootAccount
lti_context_copy_notice:
  state: hidden
  shadow: true
  applies_to: RootAccount
  display_name: Send LtiContextCopyNotices during Content Migrations
  description: |-
    Send a Platform Notice to LTI 1.3 tools that have subscribed
    to the LtiContextCopyNotice notice type when course copies or other content imports happen.
    Replaces the need for using the 1.1 Content Migration tool configuration.
  environments:
    development:
      state: allowed_on
    ci:
      state: allowed_on
lti_deep_linking_line_items:
  state: hidden
  display_name: LTI Deep Linking Line Items
  description: If enabled, creates assignments from LineItems in deep link messages.
  applies_to: RootAccount
lti_deep_linking_module_index_menu_modal:
  state: hidden
  display_name: LTI Deep Linking for Module Index Menu
  description: If enabled, allows deep linking from the module index via a modal.
  applies_to: RootAccount
lti_deployment_id_in_login_request:
  state: hidden
  applies_to: RootAccount
  display_name: Send lti_deployment_id in the LTI login request
  description: |-
    When enabled the lti_deployment_id will be sent in the LTI 1.3 login request.
    When disabled both deployment_id and lti_deployment_id will be sent.
  environments:
    development:
      state: allowed_on
    ci:
      state: allowed_on
lti_find_external_tool_prefer_original_client_id:
  state: hidden
  applies_to: RootAccount
  display_name: Prefer LTI tools with a matching client ID when finding an external tool
  description: |-
    When possible, the LTI tool finding logic will prefer tools installed from the same
    developer key as the original tool. This prevents the edge case where multiple developer
    keys share the same domain, and a tool from the wrong developer key would be matched first.
lti_oidc_missing_cookie_retry:
  state: hidden
  shadow: true
  applies_to: RootAccount
  display_name: Retry LTI OIDC launches that fail due to missing cookies
  description: |-
    If enabled, Canvas will retry LTI OIDC launches that fail due to missing cookies.
    Safari tracking protection sometimes blocks cookies from being set to authorize the endpoint.
    To fix this, we resubmit the request with a form.
  environments:
    development:
      state: allowed_on
    test:
      state: allowed_on
    ci:
      state: allowed_on
lti_registrations_discover_page:
  state: hidden
  shadow: true
  applies_to: RootAccount
  display_name: LTI Apps Discover Page
  description: When enabled, the LTI Apps Discover page will be available in the Apps page.
  environments:
    development:
      state: allowed_on
    ci:
      state: allowed_on
  custom_transition_proc: lti_registrations_discover_page_hook
lti_registrations_next:
  state: hidden
  shadow: true
  applies_to: RootAccount
  display_name: LTI Apps Page Features In-Development
  description: When enabled, the LTI Apps page will have features that are currently in-development.
  environments:
    development:
      state: allowed_on
    ci:
      state: allowed_on
lti_registrations_page:
  state: hidden
  beta: true
  applies_to: RootAccount
  display_name: LTI Apps Page
  description: When enabled, the LTI Apps page will be available in the Account navigation sidebar.
  environments:
    development:
      state: allowed_on
    ci:
      state: allowed_on
lti_registrations_usage_data:
  state: hidden
  shadow: true
  applies_to: RootAccount
  display_name: LTI Apps - Usage Data
  description: When enabled, the Usage Data tab will appear in Canvas Apps.
  environments:
    development:
      state: allowed_on
    ci:
      state: allowed_on
lti_report_multiple_schema_validation_errors:
  state: hidden
  shadow: true
  applies_to: SiteAdmin
  display_name: Return multiple json schema validation errors at once (not just the first one).
  description: INTEROP-8899. This is a low risk change, because tools should not depend on error messages coming from json schema validator.
  environments:
    ci:
      state: allowed_on
    test:
      state: allowed_on
    development:
      state: allowed_on
    production:
      state: allowed_on
lti_resource_link_id_speedgrader_launches_reference_assignment:
  state: hidden
  applies_to: RootAccount
  display_name: Make SpeedGrader LTI submission launches use assignment (not tool) resource_link_id
  description: |-
    When enabled, LTI 1.1 SpeedGrader launches will set the resource_link_id and
    resource_link_title to the assignment opaque identifier and assignment
    title. With the feature flag off, in SpeedGrader launches, resource_link_id
    and resource_link_title reference the tool (not the assignment) for
    non-NewQuizzes LTI 1.1 tools.
lti_toggle_placements:
  state: hidden
  applies_to: RootAccount
  display_name: Allow LTI Placement Toggling
  description: |-
    When enabled, admins can enable or disable existing placements for any
    LTI tool installed on the External Apps page (previously only allowed
    for 1.1 tools to assist with migration to 1.3). Changes to placement
    status for 1.3 tools made on this page will be reset by any changes to the LTI
    developer key, including changes made by Instructure to global inherited keys.
  environments:
    development:
      state: allowed_on
    ci:
      state: allowed_on
lti_tools_from_federated_parents:
  state: hidden
  display_name: Show LTI tools from federated parent accounts
  description: |-
    If enabled, LTI tools installed in federated parent accounts will be
    available / visible in child accounts.
  applies_to: SiteAdmin
lti_variable_expansions_use_group_course_as_course:
  state: hidden
  shadow: true
  applies_to: RootAccount
  display_name: "LTI Variable Expansions: Use Group's Course as Course"
  description: >-
    If enabled, if an LTI tool is launched in the context of Course-based Group (Group within a Course), Course-related LTI variable expansions will use
    the Group's Course as the Course. If disabled, legacy behavior will apply -- Course-related LTI variable expansions will only apply when the Course
    is the direct context of the launch.
  environments:
    development:
      state: allowed_on
    test:
      state: allowed_on
    ci:
      state: allowed_on
microsoft_group_enrollments_syncing:
  state: hidden
  display_name: Microsoft Group enrollment syncing
  description: |-
    If enabled, syncing course enrollments to Microsoft Groups will be
    available. Account admins may enable this in account settings.
  applies_to: RootAccount
platform_notification_service:
  state: hidden
  shadow: true
  applies_to: RootAccount
  display_name: Enable Platform Notification Service
  description: >-
    When on, 1Edtech Platform Notification service (used to subscribe tools for notices, list existing notice handlers, notify subscribed tools, etc.) will
    be enabled.
  environments:
    development:
      state: allowed_on
    test:
      state: allowed_on
    ci:
      state: allowed_on
refactor_custom_variables:
  state: hidden
  shadow: true
  applies_to: RootAccount
  display_name: Refactor custom variables to make substitution controllerless.
  description: |-
    Some of the custom variables used a controller instance for substitution.
    That is not available in background jobs, so in PNS notices and content migration.
    This feature flag will refactor the custom variables to make most if the variable substitutions controllerless.
  environments:
    development:
      state: allowed_on
    test:
      state: allowed_on
    ci:
      state: allowed_on
remove_unwanted_lti_validation_claims:
  state: hidden
  applies_to: SiteAdmin
  display_name: Do not include validation_context and errors claims in LTI Launches
  description: If enabled, the unwanted LTI validation claims like validation_context and errors will not be included in every LTI launch.
  environments:
    development:
      state: allowed_on
    test:
      state: allowed_on
    ci:
      state: allowed_on
top_navigation_placement:
  state: hidden
  applies_to: RootAccount
  display_name: Top Navigation Placement
  description: Enables top_navigation LTI placement. (LTI 1.3 Only)
  environments:
    development:
      state: allowed_on
    ci:
      state: allowed_on
tune_lti_context_id_history_query:
  state: hidden
  applies_to: RootAccount
  display_name: Use alternate settings for LTI Context.id.history query
  description: |-
    In some accounts with a large number of content migrations, the query
    that populates the Context.id.history LTI variable expansion may
    time out regardless of the length of the history for that context.
    Enabling this will run the query with different settings that may
    improve performance. Caution: for some accounts where this query
    doesn't already time out, enabling this may cause the query to take
    much longer and even time out.